version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.prod # Using the same env file as backend for DB credentials
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword # Ensure the database is created
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stock_app_network
    restart: unless-stopped

  backend:
    image: abdou2012/postefinances_stock_appv1:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    volumes:
      - ./users.xlsx:/app/users.xlsx # Mount users.xlsx from host root to container /app/users.xlsx
      - ./backend/stock.xlsx:/app/stock.xlsx # Mount stock.xlsx from backend dir to container /app/stock.xlsx
    restart: unless-stopped
    networks:
      - stock_app_network

  frontend:
    image: abdou2012/postefinances_stock_appv1:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://backend:8000/api # Corrected for Docker network communication
        NEXT_PUBLIC_API_URL_HOST: http://localhost:8000/api
    env_file:
      - ./frontend/.env.prod # NEW: Add env_file for frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - stock_app_network

networks:
  stock_app_network:
    driver: bridge

volumes:
  postgres_data: